name: search_alerts
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

analyzer:
  enable-experiment:
    - non-nullable
    
dependencies:
  flutter:
    sdk: flutter
  provider: ^4.3.2+3
  http: ^0.12.2
  cupertino_icons: ^1.0.0
  shared_preferences: any
  flushbar: ^1.10.4
  html:
  webview_flutter: 0.3.20+2
  flutter_inappwebview: ^4.0.0+4
  flutter_search_bar: ^2.1.0
  image_picker: ^0.6.7+20

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/images/

  uses-material-design: true